### ISSUE TITLE
Graphics do not show up in SGB mode

### ISSUE THREAD

**Issue by pokemonfan6498** [m-mayday/game-translations#1]
i saw translation for atelier marie gb getting released so i tested it out on retroarch using mgba core and i found that for some reason there's nothing but black screen while in sgb mode while sound was present indicating that game works but doesn't display graphics for some reason i hope this issue will be fixed and for notation it works in dmg mode

**Comment by m-mayday** [comment]
I was able to replicate it but I got the same issue with an unpatched original game, is that the same for you?
I also tried with other emulators (BGB, SameBoy) in SGB mode and had no issues except when playing with some settings in BGB, which ended up with a white screen which also affected the original game.

Seems to be a problem with the game/emulator, not the patch itself.

**Comment by pokemonfan6498** [comment]
it works on bgb but for some reason doesn't show up on retroarch mgba core
i was testing on Nintendo switch and yes original unmodified rom does not
work on mgba core too but it surprisingly works on VBA-M core

**Comment by m-mayday** [comment]
I tested in dmg mode with the original game in mgba core and there are still some problems with text boxes not showing up or displaying incorrectly. It happens with the regular mgba, outside of retroarch.

I've updated the readme to warn people about this. Since it's not an issue with the patch, I'm going to close this issue but thanks for the heads up!

**Comment by Squall-Leonhart** [comment]
there seem to be some issues with palette emulation in mGBA's SGB mode that have evaded detection till now, neither the sprites, obj or bg tiles are setting the palette on change so you get a black screen with the occasional right to left scrolling white silhouette in the intro screens.
