### ISSUE TITLE
Menu transitions, a request. 

### ISSUE THREAD

**Issue by riggles1** [m-mayday/game-translations#3]
I was wondering if something could be done about the fade to white transition between the various menu screens. Feels like there's room to make the menuing a lot snappier if that transition could be removed or shortened. Not the end of the world, but it would be nice.

Just throwing it out there as a QoL consideration, implementation is likely not easy at all I imagine. 
In either case, the game plays great with a flashcart, thank you! :)

**Comment by m-mayday** [comment]
I honestly have no idea on how to do this for menus specifically, but I could manage something enabling double speed on game start. I gave it a quick test and it does improve the transition speed but it also speeds up the (few) voice lines the game has. If I manage to work around that particular issue, I'll upload a new version.

PS: Double Speed increases power consumption, so keep that in mind if playing on real hardware.

**Comment by riggles1** [comment]
Smart solution if it works out, but otherwise don't worry about it and close this as not planned. It's a very minor thing and not like a bug or anything after all.

**Comment by m-mayday** [comment]
Lucky for you, I can be very stubborn! I managed to fix the issue with the voice lines so I'll upload a new version as soon as I have some time and update the readme with some considerations for this version. I'll keep the issue open for now until it's uploaded.

**Comment by AngryScotsmanGaming** [comment]
'lucky for you, I can be very stubborn!'

things you love to see when a dev has been brought forward an idea your work has not been recognised enough thank you!

**Comment by m-mayday** [comment]
> your work has not been recognised enough thank you!

Thank you!

The double speed version has been uploaded, be sure to check it out, as well as the README.
I'm closing this issue, hope the new version makes it a bit faster for you!

**Comment by riggles1** [comment]
Thank you! It works perfectly on a real Gameboy Color btw, there's no risk to playing it double speed considering other MBC5 mapper games are double speed already, MBC5 was the first mapper that officially was approved for the mode.
So the readme HW warning is a bit much.

Like you said, the side effect is that music speeds up a bit during the transition animation, but it's so snappy that it's more than worth it. Music and gameplay speed remain intact, haven't encountered any bugs either. Thanks again : D

**Comment by m-mayday** [comment]
Glad it's working fine!
I'll tone down the warning a bit. Got a little traumatized reading about some other risks when trying to get this working but they only apply when switching modes while the game is active, and I ended up moving away from that approach.
